<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Events Calendar</title>
    <link rel="stylesheet" href="dashboard.css">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://unpkg.com/lucide@latest"></script>
    <style>
        .calendar-nav-btn:hover {
            background-color: #d1d5db !important;
        }
        .calendar-day {
            padding: 8px;
            background-color: white;
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            text-align: center;
            cursor: pointer;
            transition: all 0.2s ease;
        }
        .calendar-day:hover {
            background-color: #f3f4f6;
            border-color: #3b82f6;
        }
        .calendar-day.other-month {
            color: #d1d5db;
            background-color: #f9fafb;
        }
        .calendar-day.has-event {
            background-color: #dbeafe;
            border-color: #3b82f6;
            font-weight: 600;
        }
        .calendar-day.today {
            background-color: #3b82f6;
            color: white;
            border-color: #2563eb;
        }
    </style>
</head>
<body>
    <div class="dashboard">
        <!-- Sidebar -->
        <?php include('sidebar.php'); ?>
        
        <!-- Main Content -->
        <main class="main-content">
<div class="card">
  <h2 class="section-title">Library Events Calendar</h2>
  <div class="section-content">
    <div id="calendar-container" style="margin-top: 20px;">
      <div id="calendar-header" style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
        <h3 id="current-month" style="margin: 0; font-size: 1.3rem;"></h3>
        <div style="display: flex; gap: 10px;">
          <button id="prev-month" class="calendar-nav-btn" style="padding: 5px 10px; background-color: #e5e7eb; border: none; border-radius: 4px; cursor: pointer;">
            <i data-lucide="chevron-left"></i>
          </button>
          <button id="today-btn" class="calendar-nav-btn" style="padding: 5px 10px; background-color: #e5e7eb; border: none; border-radius: 4px; cursor: pointer;">
            Today
          </button>
          <button id="next-month" class="calendar-nav-btn" style="padding: 5px 10px; background-color: #e5e7eb; border: none; border-radius: 4px; cursor: pointer;">
            <i data-lucide="chevron-right"></i>
          </button>
        </div>
      </div>
      
      <div id="calendar" style="display: grid; grid-template-columns: repeat(7, 1fr); gap: 5px;">
        <!-- Calendar days will be generated by JavaScript -->
      </div>
    </div>
    
    <div id="event-details-modal" style="display: none; position: fixed; top: 0; left: 0; right: 0; bottom: 0; background-color: rgba(0,0,0,0.5); z-index: 1000; justify-content: center; align-items: center;">
      <div style="background-color: white; padding: 20px; border-radius: 8px; width: 90%; max-width: 500px;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
          <h3 id="event-modal-title" style="margin: 0;">Event Details</h3>
          <button id="close-event-modal" style="background: none; border: none; cursor: pointer;">
            <i data-lucide="x"></i>
          </button>
        </div>
        <div id="event-modal-content">
          <!-- Event details will be inserted here -->
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    // Initialize calendar
    let currentDate = new Date();
    let currentMonth = currentDate.getMonth();
    let currentYear = currentDate.getFullYear();
    
    const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
    const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
    
    // Sample events data (in a real app, this would come from an API)
    const events = [
      {
        id: 1,
        title: "Book Club Meeting",
        date: new Date(currentYear, currentMonth, 15),
        time: "6:00 PM",
        location: "Library Meeting Room A",
        description: "Monthly book club meeting discussing this month's selected novel."
      },
      {
        id: 2,
        title: "Children's Story Time",
        date: new Date(currentYear, currentMonth, 8),
        time: "10:00 AM",
        location: "Children's Section",
        description: "Interactive story time for children ages 3-7."
      },
      {
        id: 3,
        title: "Author Talk: Jane Doe",
        date: new Date(currentYear, currentMonth, 22),
        time: "7:00 PM",
        location: "Library Auditorium",
        description: "Bestselling author Jane Doe discusses her new book and writing process."
      },
      {
        id: 4,
        title: "Tech Workshop: Intro to Coding",
        date: new Date(currentYear, currentMonth, 5),
        time: "2:00 PM",
        location: "Computer Lab",
        description: "Beginner-friendly introduction to programming concepts."
      }
    ];
    
    // Generate calendar
    function generateCalendar(month, year) {
      const calendarEl = document.getElementById('calendar');
      const currentMonthEl = document.getElementById('current-month');
      
      // Set current month header
      currentMonthEl.textContent = `${monthNames[month]} ${year}`;
      
      // Clear previous calendar
      calendarEl.innerHTML = '';
      
      // Add day headers
      dayNames.forEach(day => {
        const dayHeader = document.createElement('div');
        dayHeader.textContent = day;
        dayHeader.style.textAlign = 'center';
        dayHeader.style.fontWeight = 'bold';
        dayHeader.style.padding = '5px';
        dayHeader.style.backgroundColor = '#f3f4f6';
        calendarEl.appendChild(dayHeader);
      });
      
      // Get first day of month and total days in month
      const firstDay = new Date(year, month, 1).getDay();
      const daysInMonth = new Date(year, month + 1, 0).getDate();
      
      // Add empty cells for days before first day of month
      for (let i = 0; i < firstDay; i++) {
        const emptyCell = document.createElement('div');
        emptyCell.style.height = '80px';
        emptyCell.style.backgroundColor = '#f9fafb';
        calendarEl.appendChild(emptyCell);
      }
      
      // Add cells for each day of month
      for (let day = 1; day <= daysInMonth; day++) {
        const dayCell = document.createElement('div');
        dayCell.style.height = '80px';
        dayCell.style.padding = '5px';
        dayCell.style.border = '1px solid #e5e7eb';
        dayCell.style.position = 'relative';
        
        // Highlight current day
        const currentDay = currentDate.getDate();
        const currentMonthToday = currentDate.getMonth();
        const currentYearToday = currentDate.getFullYear();
        
        if (day === currentDay && month === currentMonthToday && year === currentYearToday) {
          dayCell.style.backgroundColor = '#dbeafe';
        }
        
        // Add day number
        const dayNumber = document.createElement('div');
        dayNumber.textContent = day;
        dayNumber.style.fontWeight = 'bold';
        dayNumber.style.marginBottom = '5px';
        dayCell.appendChild(dayNumber);
        
        // Add events for this day
        const dayEvents = events.filter(event => {
          return event.date.getDate() === day && 
                 event.date.getMonth() === month && 
                 event.date.getFullYear() === year;
        });
        
        dayEvents.forEach(event => {
          const eventEl = document.createElement('div');
          eventEl.textContent = event.title;
          eventEl.style.fontSize = '0.8rem';
          eventEl.style.padding = '2px 5px';
          eventEl.style.marginBottom = '2px';
          eventEl.style.backgroundColor = '#3b82f6';
          eventEl.style.color = 'white';
          eventEl.style.borderRadius = '3px';
          eventEl.style.cursor = 'pointer';
          eventEl.style.overflow = 'hidden';
          eventEl.style.textOverflow = 'ellipsis';
          eventEl.style.whiteSpace = 'nowrap';
          eventEl.dataset.eventId = event.id;
          
          eventEl.addEventListener('click', () => showEventDetails(event.id));
          
          dayCell.appendChild(eventEl);
        });
        
        calendarEl.appendChild(dayCell);
      }
    }
    
    // Show event details modal
    function showEventDetails(eventId) {
      const event = events.find(e => e.id === eventId);
      if (!event) return;
      
      const modal = document.getElementById('event-details-modal');
      const modalTitle = document.getElementById('event-modal-title');
      const modalContent = document.getElementById('event-modal-content');
      
      modalTitle.textContent = event.title;
      
      modalContent.innerHTML = `
        <p><strong>Date:</strong> ${event.date.toLocaleDateString()}</p>
        <p><strong>Time:</strong> ${event.time}</p>
        <p><strong>Location:</strong> ${event.location}</p>
        <p><strong>Description:</strong> ${event.description}</p>
        <div style="margin-top: 20px;">
          <button id="rsvp-btn" style="padding: 8px 16px; background-color: #3b82f6; color: white; border: none; border-radius: 4px; cursor: pointer;">
            RSVP for this Event
          </button>
        </div>
      `;
      
      modal.style.display = 'flex';
      
      // Add event listener to RSVP button
      document.getElementById('rsvp-btn')?.addEventListener('click', () => {
        alert(`You have successfully RSVP'd for "${event.title}"`);
        modal.style.display = 'none';
      });
    }
    
    // Navigation buttons
    document.getElementById('prev-month').addEventListener('click', () => {
      currentMonth--;
      if (currentMonth < 0) {
        currentMonth = 11;
        currentYear--;
      }
      generateCalendar(currentMonth, currentYear);
    });
    
    document.getElementById('next-month').addEventListener('click', () => {
      currentMonth++;
      if (currentMonth > 11) {
        currentMonth = 0;
        currentYear++;
      }
      generateCalendar(currentMonth, currentYear);
    });
    
    document.getElementById('today-btn').addEventListener('click', () => {
      currentDate = new Date();
      currentMonth = currentDate.getMonth();
      currentYear = currentDate.getFullYear();
      generateCalendar(currentMonth, currentYear);
    });
    
    // Close modal button
    document.getElementById('close-event-modal').addEventListener('click', () => {
      document.getElementById('event-details-modal').style.display = 'none';
    });
    
    // Initialize calendar
    generateCalendar(currentMonth, currentYear);
    lucide.createIcons();
  });
</script>
        </main>
    </div>
    <script>
        // Initialize Lucide icons
        if (typeof lucide !== 'undefined') {
            lucide.createIcons();
        }
    </script>
</body>
</html>